language: node_js

node_js:
  - "6"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "npm start &"
  - sleep 3

cache:
    directories:
        - node_modules

script:
  - npm run lint
  - npm run build
  - npm test
